---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: shortify
  name: shortify
spec:
  replicas: 5
  selector:
    matchLabels:
      app: shortify
  template:
    metadata:
      labels:
        app: shortify
    spec:
      containers:
        - name: shortify
          image: shortify:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: shortify-env-vars
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /core/healthz/
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
